name: Build using Nix

on:
  push:
    branches: ['main']

jobs:
  build-and-run:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-22.05

      - name: Build project
        run: nix-build

